# otel-collector-config.yml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp/prometheus:
    endpoint: prometheus:8889

  otlp/loki:
    endpoint: loki:3100

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/jaeger, otlp/tempo ]

    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/prometheus ]

    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/loki ]


